package main

import (
	"bufio"
	"context"
	"flag"
	"fmt"
	"io"
	"math/rand"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"sync"
	"time"
)

var roomIDRegex = regexp.MustCompile(`\[ROOM_ID:\s*(.*?)\]`)
var roomMetaRegex = regexp.MustCompile(`\[ROOM_META:\s*(\S+)\s+(public|private)\]`)

const privateRoomPassword = "password123"

type RoomRef struct {
	ID        string
	IsPrivate bool
	Password  string
}

type Bot struct {
	ID     string
	Cmd    *exec.Cmd
	Stdin  io.WriteCloser
	Stdout io.ReadCloser
	Rooms  []RoomRef // Known room IDs
	Synced bool      // Has the bot synchronized with the global Telemetry mesh?
	mu     sync.Mutex
}

func main() {
	rand.Seed(time.Now().UnixNano())

	var numClients int
	var simDurationStr string
	var baseListenPort int
	var baseSocksPort int
	flag.IntVar(&numClients, "clients", 3, "Number of concurrent Tor headless clients to spawn")
	flag.StringVar(&simDurationStr, "duration", "15m", "Duration of the simulation (e.g., 30m, 2h)")
	flag.IntVar(&baseListenPort, "base-listen-port", 0, "Base local libp2p listen port for telemetry and bots")
	flag.IntVar(&baseSocksPort, "base-socks-port", 0, "Base Tor SOCKS port for telemetry and bots")
	flag.Parse()

	duration, err := time.ParseDuration(simDurationStr)
	if err != nil {
		fmt.Printf("Invalid duration: %v\n", err)
		os.Exit(1)
	}

	simID := time.Now().Format("20060102_150405")
	logDir := filepath.Join("logs", fmt.Sprintf("simulation_%s", simID))
	os.MkdirAll(logDir, 0755)
	if baseListenPort == 0 {
		baseListenPort = 4001 + rand.Intn(1000)*10
	}
	if baseSocksPort == 0 {
		baseSocksPort = 46000 + rand.Intn(1000)*10
	}

	fmt.Printf("========== ANIMASOLA CHAOS ENGINE ==========\n")
	fmt.Printf("Duration: %s | Clients: %d\n", duration, numClients)
	fmt.Printf("Logs:     %s\n", logDir)
	fmt.Printf("============================================\n")

	ctx, cancel := context.WithTimeout(context.Background(), duration)
	defer cancel()

	telemetryArgs := []string{"run", "cmd/telemetry/main.go", "-listen-port", fmt.Sprintf("%d", baseListenPort), "-socks-port", fmt.Sprintf("%d", baseSocksPort), "chaos_admin"}
	telemetryExecutable := "go"
	if customTelemetry := strings.TrimSpace(os.Getenv("ANIMASOLA_TELEMETRY_BIN")); customTelemetry != "" {
		telemetryExecutable = customTelemetry
		telemetryArgs = []string{"-listen-port", fmt.Sprintf("%d", baseListenPort), "-socks-port", fmt.Sprintf("%d", baseSocksPort), "chaos_admin"}
	}

	// 1. Spawan Telemetry Collector
	telemetryCmd := exec.CommandContext(ctx, telemetryExecutable, telemetryArgs...)
	telemetryOut, _ := os.Create(filepath.Join(logDir, "telemetry.jsonl"))
	defer telemetryOut.Close()
	telemetryCmd.Stdout = telemetryOut
	telemetryCmd.Stderr = telemetryOut
	if err := telemetryCmd.Start(); err != nil {
		fmt.Printf("Fatal: failed to spawn telemetry daemon: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("[+] Telemetry Mesh Collector started in background.")

	// 2. Spawn headless clients
	var bots []*Bot
	var syncWg sync.WaitGroup
	syncWg.Add(numClients)

	for i := 1; i <= numClients; i++ {
		botID := fmt.Sprintf("sim_bot_%d", i)
		listenPort := baseListenPort + i
		socksPort := baseSocksPort + i
		headlessArgs := []string{"run", "cmd/headless/main.go", "-listen-port", fmt.Sprintf("%d", listenPort), "-socks-port", fmt.Sprintf("%d", socksPort), botID}
		headlessExecutable := "go"
		if customHeadless := strings.TrimSpace(os.Getenv("ANIMASOLA_HEADLESS_BIN")); customHeadless != "" {
			headlessExecutable = customHeadless
			headlessArgs = []string{"-listen-port", fmt.Sprintf("%d", listenPort), "-socks-port", fmt.Sprintf("%d", socksPort), botID}
		}
		botLog, _ := os.Create(filepath.Join(logDir, fmt.Sprintf("%s.log", botID)))
		cmd := exec.CommandContext(ctx, headlessExecutable, headlessArgs...)
		stdin, _ := cmd.StdinPipe()
		stdout, _ := cmd.StdoutPipe()
		cmd.Stderr = botLog // Pipe stderr raw

		bot := &Bot{
			ID:     botID,
			Cmd:    cmd,
			Stdin:  stdin,
			Stdout: stdout,
		}
		bots = append(bots, bot)

		if err := cmd.Start(); err != nil {
			fmt.Printf("Failed to spawn %s: %v\n", botID, err)
			syncWg.Done() // Decrement WaitGroup if spawn fails
			continue
		}

		// Read stdout async to parse Room IDs generated by this bot
		go drainAndParseStdout(bot, botLog, &syncWg)
		fmt.Printf("[+] Spawned %s ...\n", botID)
	}

	// Phase 23: Deterministic Sync Barrier instead of blind sleep
	fmt.Printf("[*] Waiting for %d bots to achieve Tor Telemetry Mesh Consensus...\n", numClients)
	syncDone := make(chan struct{})
	go func() {
		syncWg.Wait()
		close(syncDone)
	}()

	select {
	case <-syncDone:
		fmt.Printf("[+] Consensus Reached! All bots connected to Global Telemetry.\n")
	case <-time.After(30 * time.Second):
		fmt.Printf("[!] Consensus Timeout! Proceeding with degraded mesh.\n")
	}

	fmt.Printf("================= COMMENCING CHAOS =================\n")

	// 3. Chaos Event Loop
	ticker := time.NewTicker(15 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			fmt.Println("\n[*] Simulation duration reached. Sending kill signals to swarm...")
			for _, b := range bots {
				fmt.Fprintf(b.Stdin, "DISCONNECT\n")
			}
			time.Sleep(5 * time.Second)
			fmt.Println("[*] Execution Terminated.")
			return
		case <-ticker.C:
			// Pick a random bot to inflict an action
			bot := bots[rand.Intn(len(bots))]
			action := rand.Intn(100)

			if action < 20 { // 20% Create a room (Public or Private)
				roomName := fmt.Sprintf("chaos_%d", rand.Intn(10000))
				if rand.Intn(2) == 0 {
					fmt.Printf("[CHAOS] %s creating Public Room: %s\n", bot.ID, roomName)
					sendCommand(bot, "CREATE_PUBLIC "+roomName)
				} else {
					fmt.Printf("[CHAOS] %s creating Private Room: %s\n", bot.ID, roomName)
					sendCommand(bot, "CREATE_PRIVATE "+roomName+" "+privateRoomPassword)
				}
			} else if action < 60 { // 40% Send a message to a known room
				bot.mu.Lock()
				if len(bot.Rooms) > 0 {
					targetRoom := bot.Rooms[rand.Intn(len(bot.Rooms))]
					msg := fmt.Sprintf("Ping from %s at %d", bot.ID, time.Now().Unix())
					sendCommand(bot, "CHAT "+targetRoom.ID+" "+msg)
				}
				bot.mu.Unlock()
			} else if action < 90 { // 30% Exchange Rooms: Have one bot join another bot's room
				bot.mu.Lock()
				if len(bot.Rooms) > 0 {
					sharedRoom := bot.Rooms[rand.Intn(len(bot.Rooms))]
					otherBot := bots[rand.Intn(len(bots))]
					if otherBot.ID != bot.ID {
						fmt.Printf("[CHAOS] Routing %s to join %s's room %s\n", otherBot.ID, bot.ID, sharedRoom.ID)
						if sharedRoom.IsPrivate {
							sendCommand(otherBot, "JOIN_PRIVATE "+sharedRoom.ID+" "+sharedRoom.Password)
						} else {
							sendCommand(otherBot, "JOIN_PUBLIC "+sharedRoom.ID)
						}
						otherBot.mu.Lock()
						addRoom(otherBot, sharedRoom)
						otherBot.mu.Unlock()
					}
				}
				bot.mu.Unlock()
			} else { // 10% Disconnect temporarily to force network tear down
				bot.mu.Lock()
				if len(bot.Rooms) > 0 {
					targetRoom := bot.Rooms[rand.Intn(len(bot.Rooms))]
					fmt.Printf("[CHAOS] %s dropping P2P topic %s\n", bot.ID, targetRoom.ID)
					sendCommand(bot, "LEAVE "+targetRoom.ID)

					// Removing gracefully from active array
					for i, r := range bot.Rooms {
						if r.ID == targetRoom.ID {
							bot.Rooms = append(bot.Rooms[:i], bot.Rooms[i+1:]...)
							break
						}
					}
				}
				bot.mu.Unlock()
			}
		}
	}
}

func drainAndParseStdout(bot *Bot, logFile io.Writer, wg *sync.WaitGroup) {
	scanner := bufio.NewScanner(bot.Stdout)
	for scanner.Scan() {
		line := scanner.Text()
		fmt.Fprintf(logFile, "%s\n", line) // Archive the raw line

		if strings.Contains(line, "[TELEMETRY_SYNCED]") {
			bot.mu.Lock()
			if !bot.Synced {
				bot.Synced = true
				wg.Done()
			}
			bot.mu.Unlock()
		}

		metaMatches := roomMetaRegex.FindStringSubmatch(line)
		if len(metaMatches) == 3 {
			addRoom(bot, RoomRef{
				ID:        strings.TrimSpace(metaMatches[1]),
				IsPrivate: metaMatches[2] == "private",
				Password:  privateRoomPassword,
			})
			continue
		}

		// Extract Room ID footprints
		matches := roomIDRegex.FindStringSubmatch(line)
		if len(matches) > 1 {
			addRoom(bot, RoomRef{ID: strings.TrimSpace(matches[1])})
		}
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintf(logFile, "[PROCESS_ERROR] Stdout parsing failed: %v\n", err)
	}
}

// sendCommand forces a strict POSIX line ending into the subprocess via the pipe.
func sendCommand(bot *Bot, cmd string) {
	if bot.Stdin != nil {
		bot.Stdin.Write([]byte(cmd + "\n"))
	}
}

func addRoom(bot *Bot, room RoomRef) {
	for _, existing := range bot.Rooms {
		if existing.ID == room.ID {
			return
		}
	}
	bot.Rooms = append(bot.Rooms, room)
}
